### ISSUE TITLE
Doesn't work with Android Studio 4.1 Canary

### ISSUE THREAD

**Issue by sinlos** [itkacher/OkHttpProfiler#17]
Android Studio 4.1 Canary 6
Build #AI-193.6911.18.41.6381907, built on April 9, 2020

Plugin: 1.0.9
Library: 1.0.7

`java.lang.IncompatibleClassChangeError: Found interface com.android.ddmlib.Client, but class was expected
	at com.itkacher.DebuggerToolWindowFactory.createProcessList(DebuggerToolWindowFactory.kt:169)
	at com.itkacher.DebuggerToolWindowFactory.attachToDevice(DebuggerToolWindowFactory.kt:159)
	at com.itkacher.DebuggerToolWindowFactory.updateDeviceList(DebuggerToolWindowFactory.kt:150)
	at com.itkacher.DebuggerToolWindowFactory.access$updateDeviceList(DebuggerToolWindowFactory.kt:22)
	at com.itkacher.DebuggerToolWindowFactory$initDeviceList$2.bridgeChanged(DebuggerToolWindowFactory.kt:85)
	at com.android.ddmlib.AndroidDebugBridge.addDebugBridgeChangeListener(AndroidDebugBridge.java:591)
	at com.itkacher.DebuggerToolWindowFactory.initDeviceList(DebuggerToolWindowFactory.kt:81)
	at com.itkacher.DebuggerToolWindowFactory.createToolWindowContent(DebuggerToolWindowFactory.kt:59)`

**Comment by gektor650** [comment]
Added description [here](https://github.com/itkacher/OkHttpProfiler/issues/19) and in the readme. 
I thought Google will fix changing from the interface to the client. But they didn't.
